name 'purplehazech-mediawiki'
version '1.0.0'

author 'Lucas S. Bickel'
license 'AGPL'
project_page 'https://github.com/purplehazech/puppet-mediawiki'
source 'https://github.com/purplehazech/puppet-mediawiki'
summary 'mediawiki, with some bells and whistles'
description 'We need a wiki at radio rabe. This installs mediawiki and has support for some modules.'
dependency 'hairmare/webapp_config', '>=1.0.0'
dependency 'purplehazech/apache', '>=0.5.0'
dependency 'purplehazech/layman', '>=0.0.1'
dependency 'puppetlabs/stdlib', '>=3.2.0'
